import Head from "next/head";
import React, { useEffect } from "react";
import Socket from "../socket";

export default function Home() {
  useEffect(() => Socket.init(), []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
